# Q1. Why is numpy better than list

1. Numpy consumes less memory than list.
2. Numpy takes less execution time than list.

# Q2. How do you define shape, size of an array

In [3]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print("Total Dimension : ",a.ndim)
print("Total shape : ",a.shape)
print("Total size : ",a.size)

Total Dimension :  2
Total shape :  (2, 3)
Total size :  6


# Q3. Difference between zeros, ones, eye, diag functions. Provide examples.

In [6]:
# Zeros ->This function create an array(either one dimensional or multi dimensional) and fill all values with zeros
a=np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
# Ones-> This function creates an array(either one dimensional or multi dimensional) and fill all the values with one.
a=np.ones((3,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
# eye-> This function creates an array with all the diagnol elements as 1 and rest 0.
a=np.eye(3,3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
# diag-> This function creates a two dimensional array with all the diagnom elements as the given value and rest are the zeros.
a=np.diag([1,2,3,4,5])
a

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

# Q4. What is randint function. How can you fix your random data.

In [12]:
# Randint function is used to generate a random number between a given range.
a=np.random.randint(1,20,6)
a

array([ 9, 15,  2, 16, 19, 16])

In [18]:
# Random data is fixed with the help of seed function.
np.random.seed(2)
a=np.random.randint(1,20,6)
a

array([ 9, 16, 14,  9, 12, 19])

# Q5. Difference between linspace and unique function. 

In [13]:
# Linspace function return evenly spaced numbers over a specified interval.
a=np.linspace(1,4,6)
a

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

In [14]:
# Unique function return unique elements as a sorted array.
a=np.unique([1,3,2,4,5,2,6,4,6,7,5,1])
a

array([1, 2, 3, 4, 5, 6, 7])

# Q6. Difference between horizontal stacking and vertical stacking. Provide example.

In [15]:
# Horizontal Stacking-> It performs horizontal stacking along with the columns.
a=np.hstack([[1,2,3,4],[5,6,7,8]])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [16]:
# Vertical Stacking -> It performs vertical stacking along with the rows.
a=np.vstack([[1,2,3,4],[5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

# Q7. How can you multiply two array in numpy.

In [21]:
# In numpy, two array are multiplied by dot function.
a=np.array([[10,20],[50,60]])
b=np.array([[2,3],[6,7]])
a.dot(b)

array([[140, 170],
       [460, 570]])

# Q8. Difference between series and dataframe.

In [31]:
# Series has only one column while DataFrame can have single or multiple columns.
import pandas as pd
a=pd.Series([10,20,30,40])
print("Series : \n")
print(a)
b=pd.DataFrame([[10,20,30,40],[50,60,70,80]])
print("DataFrame :\n")
print(b)

Series : 

0    10
1    20
2    30
3    40
dtype: int64
DataFrame :

    0   1   2   3
0  10  20  30  40
1  50  60  70  80


# Q9. Difference between loc and iloc.

In [42]:
# The loc function is used for label indexing can access multiple columns.
a=pd.Series([1,2,3,9,4,5,7,8])
display(a.loc[1:6])

1    2
2    3
3    9
4    4
5    5
6    7
dtype: int64

In [39]:
# The iloc function is used for integer indexing
a=pd.Series([1,2,3,9,4,5,7,8])
display(a.iloc[[1,3,5]])

1    2
3    9
5    5
dtype: int64

# Q10. What does value counts.

In [43]:
# value_counts function returns a series containing counts of unique values.
a=pd.Series([1,2,3,2,3,4,2,3,6,7,5,3,2,9])
a.value_counts()

2    4
3    4
1    1
4    1
6    1
7    1
5    1
9    1
dtype: int64

# Q11. How can you extract month, days and year in a date time column using pandas.

In [59]:
# Use DatetimeIndex To extract the month and year from the pandas Datetime column.
import datetime
data = {'date_time': ['2023-01-15 08:30:00', '2023-02-20 12:45:00', '2023-03-25 18:15:00']}
df = pd.DataFrame(data)
df['date_time'] = pd.to_datetime(df['date_time'])

df['month'] = df['date_time'].dt.month
df['day'] = df['date_time'].dt.day
df['year'] = df['date_time'].dt.year
print(df)

            date_time  month  day  year
0 2023-01-15 08:30:00      1   15  2023
1 2023-02-20 12:45:00      2   20  2023
2 2023-03-25 18:15:00      3   25  2023


# Q12. How do you handle missing values in a dataframe.

In [49]:
# Missing values in a DataFrame using isnull()
a=pd.Series([1,2,3,4,5,6])
a.isnull()

0    False
1    False
2    False
3    False
4    False
5    False
dtype: bool

# Q13. How do you rename column name in a dataframe.

In [51]:
# Using rename(), column name can be renamed.
a=pd.DataFrame({'Student': ['Ajay','Ayan'],
   'Batch' : ['A','B']})
a.rename(columns={'Batch':'Class'},inplace=True)
a


Student Class
0    Ajay     A
1    Ayan     B

# Q14. What are aggregate function. What is difference between pivot and pivot table and crosstab.

An aggregate function in a mathemetical computation involving a range of values that result in just a single value expressing the significance of the accumulated data it is derived from. Aggregate functions are count(),sum(),avg(),min(),max().

The pivot function in Pandas is used to reshape or transform data by rearranging the rows and columns.

The pivot_table function in Pandas is an extension of the pivot function and is specifically designed for creating spreadsheet-style pivot tables.

The crosstab function in Pandas is used to compute cross-tabulations, also known as contingency tables or pivot tables of factors.