In [1]:
import numpy as np

In [2]:
a=[1,2,3,4]
type(a)

list

In [3]:
b=np.array(a)
b

array([1, 2, 3, 4])

# How to create a user defined array ?

In [7]:
a=[]
size=int(input("Enter the size: "))
for i in range(size):
    val=input("Enter your item: ")
    a.append(val)
a

Enter the size: 4
Enter your item: a
Enter your item: b
Enter your item: c
Enter your item: d


['a', 'b', 'c', 'd']

In [7]:
a=[]
size=int(input("Enter the size: "))
for i in range(size):
    val=int(input("Enter your item: "))
    a.append(val)
b=np.array(a)
b

Enter the size: 4
Enter your item: 1
Enter your item: 2
Enter your item: 3
Enter your item: 4


array([1, 2, 3, 4])

# One Dimensional Array

In [8]:
a=[1,2,3]
b=np.array(a)
b

array([1, 2, 3])

In [10]:
print("Total Dimension : ",b.ndim) #ndim==>d dimensional data
print("Total Shape : ",b.shape)   #shape=n(rows),n(columns)
print("Total Elements : ",b.size) #size=n(rows)*n(columns)


Total Dimension :  1
Total Shape :  (3,)
Total Elements :  3


# 2-D data

In [11]:
a  = [[1,2,3] , [4,5,6] , [7,8,9]] 
b = np.array(a) 
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
print("Total Dimension : ",b.ndim) #ndim==>d dimensional data
print("Total Shape : ",b.shape)   #shape=n(rows),n(columns)
print("Total Elements : ",b.size) #size=n(rows)*n(columns)


Total Dimension :  2
Total Shape :  (3, 3)
Total Elements :  9


# Pre-defined Functions

# 1. zeros()==> It will create all values into 0. This function create an array (either one dimensional or multi dimensional) and fill all the values with zeros .

In [13]:
a=np.zeros(4)
a

array([0., 0., 0., 0.])

- Images==> Pixels (0-255) ==> 0px ==> complete black, 255px==> complete white

- Normalize ==> min_pixal_value =0, max_pixel_value=1

- Weights Initialization

In [14]:
a=np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
print("Total Dimension : ",a.ndim) #ndim==>d dimensional data
print("Total Shape : ",a.shape)   #shape=n(rows),n(columns)
print("Total Elements : ",a.size) #size=n(rows)*n(columns)


Total Dimension :  2
Total Shape :  (3, 4)
Total Elements :  12


# 2 . Ones ==> It will create an array in which all the elements are one. This function creates an array (either one dimensional or multi dimensional) and fill all the values with one . 

In [16]:
a=np.ones(4)
a

array([1., 1., 1., 1.])

In [17]:
a=np.ones((3,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
print("Total Dimension : ",a.ndim) #ndim==>d dimensional data
print("Total Shape : ",a.shape)   #shape=n(rows),n(columns)
print("Total Elements : ",a.size) #size=n(rows)*n(columns)


Total Dimension :  2
Total Shape :  (3, 4)
Total Elements :  12


Diagnol Elements==> [(0,0), (1,1),(2,2),(3,3) .......(n,n)]

Symmetric Matrix ==> n(rows) = n(columns)

Asymmetric Matrix ==> n(rows) != n(columns)


# 3 . eye ==> This function creates an array with all the digonal elements as 1 and rest are 0(In square matrix). In non-square matrix the value are still one for digonal (upto which it can draw digonal ) and rest are zero .

In [19]:
a=np.eye(3,4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [20]:
a=np.eye(4,4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# 4 . diag ==> This function creats a two dimensional array with all the digonal elements as the given value and rest are zero .

In [23]:
a=np.array([1,34,56,78])
a

array([ 1, 34, 56, 78])

In [24]:
b=np.diag(a)
b

array([[ 1,  0,  0,  0],
       [ 0, 34,  0,  0],
       [ 0,  0, 56,  0],
       [ 0,  0,  0, 78]])

In [21]:
a = np.diag([1,4,8,9])
a

array([[1, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 8, 0],
       [0, 0, 0, 9]])

# 5. Random Module

# (a) randint ==> This function is used to generate a random number between a given range .

# syntax == randint(min_value , max_value , total_numbers)

In [25]:
a = np.random.randint(1,10,3) 
a

array([8, 4, 6])

In [27]:
p= int(input("Enter min number: "))
q= int(input("Enter max number: "))
r= int(input("Enter total numbers: "))
a = np.random.randint(p,q,r)
a

Enter min number: 4
Enter max number: 9
Enter total numbers: 2


array([8, 4])

In [29]:
a = np.random.randint(int(input("Enter min number: ")),
                      int(input("Enter max number: ")),
                      int(input("Enter total numbers: ")))
a

Enter min number: 1
Enter max number: 50
Enter total numbers: 10


array([35, 13, 35, 38, 29, 36, 44, 47, 49, 33])

# (b) . rand() ==> This function is used to generate a random number between 0 to 1 .

# syntax == rand(numberof values) 

In [26]:
a = np.random.rand(5) 
a

array([0.67472902, 0.30802746, 0.17991456, 0.60282407, 0.35399269])

In [30]:
a = np.random.rand(3,4) 
a

array([[0.8427765 , 0.90266757, 0.09591891, 0.98538185],
       [0.79591489, 0.83373895, 0.33972156, 0.47509656],
       [0.06794102, 0.46251403, 0.47036767, 0.41134597]])

# (c) . randn() ==> This function is used to generate a random number from -3 to close 3 . This may return positive or negative numbers as well .

# syntax == random.randn(number of values)

In [31]:
a = np.random.randn(5) 
a

array([ 0.65853624,  0.48851192,  0.01517479,  0.79262842, -0.03707734])

In [32]:
a = np.random.rand(3,4) 
a

array([[0.85272328, 0.210548  , 0.03347873, 0.78696104],
       [0.82303006, 0.6932565 , 0.17340681, 0.96591501],
       [0.30920038, 0.66371663, 0.17281323, 0.29064654]])

# 6. seed() ==> It will fix our members. We know that randint function generates random numbers . Everytime we run the program , new set of random number is generated . So , solve this problem we will use seed function.

In [44]:
np.random.seed(2)

a=np.random.randint(1,10,3)
a

array([9, 9, 7])

# View And Copy

# View: 
This is also known as Shallow Copy. 

The view is just a view of the original array and view does not own the data. 

When we make changes to the view it affects the original array, and when changes are made to the original array it affects the view.

Example: (making a view and changing original array)

In [6]:
import numpy as np 

# creating array 
arr = np.array([2, 4, 6, 8, 10]) 

# creating view 
v = arr.view() 

# both arr and v have different id 
print("id of arr", id(arr)) 
print("id of v", id(v)) 

# changing original array 
# will effect view 
arr[0] = 12

# printing array and view 
print("original array- ", arr) 
print("view- ", v) 


id of arr 2357589249072
id of v 2357617694832
original array-  [12  4  6  8 10]
view-  [12  4  6  8 10]


# Copy: 
This is also known as Deep Copy. 

The copy is completely a new array and copy owns the data. 

When we make changes to the copy it does not affect the original array, and when changes are made to the original array it does not affect the copy.

Example: (making a copy and changing original array)

In [7]:
import numpy as np 

# creating array 
arr = np.array([2, 4, 6, 8, 10]) 

# creating copy of array 
c = arr.copy() 

# both arr and c have different id 
print("id of arr", id(arr)) 
print("id of c", id(c)) 

# changing original array 
# this will not effect copy 
arr[0] = 12

# printing array and copy 
print("original array- ", arr) 
print("copy- ", c) 


id of arr 2357589204400
id of c 2357623558768
original array-  [12  4  6  8 10]
copy-  [ 2  4  6  8 10]


# Array Owning it’s Data:
To check whether array own it’s data in view and copy we can use the fact that every NumPy array has the attribute base that returns None if the array owns the data. Else, the base attribute refers to the original object.

In [8]:
import numpy as np 

# creating array 
arr = np.array([2, 4, 6, 8, 10]) 

# creating copy of array 
c = arr.copy() 

# creating view of array 
v = arr.view() 

# printing base attribute of copy and view 
print(c.base) 
print(v.base) 


None
[ 2  4  6  8 10]


In [2]:
import numpy as np
a=np.array([10,20,30,40,50,60,70])
b=a[3:6]
b[:]=0
a

array([10, 20, 30,  0,  0,  0, 70])

In [5]:
a=np.array([10,20,30,40,50,60,70])
b=a[3:6].copy()
b[:]=0
a

array([10, 20, 30, 40, 50, 60, 70])

# Conditional Operation

In [6]:
a=np.arange(1,16)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [7]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [8]:
a<10

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False])

In [9]:
b=a<10
a[b]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
b=a>10
a[b]

array([11, 12, 13, 14, 15])

In [11]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12, 14])

In [12]:
b=np.arange(1,5)
b+2

array([3, 4, 5, 6])

In [13]:
b*2

array([2, 4, 6, 8])

In [14]:
b**2

array([ 1,  4,  9, 16], dtype=int32)

In [15]:
b**3

array([ 1,  8, 27, 64], dtype=int32)

In [3]:
a =  np.arange(1,5)

In [4]:
a=  a.reshape(2,2)

In [5]:
a

array([[1, 2],
       [3, 4]])

In [23]:
b = np.arange(5,9).reshape(2,2) 
b

array([[5, 6],
       [7, 8]])

In [24]:
a+b

array([[ 6,  8],
       [10, 12]])

In [25]:
a-b

array([[-4, -4],
       [-4, -4]])

In [26]:
a*b

array([[ 5, 12],
       [21, 32]])

In [27]:
a.dot(b) 

array([[19, 22],
       [43, 50]])

In [28]:
a=np.arange(1,5)
a

array([1, 2, 3, 4])

In [29]:
np.max(a)

4

In [30]:
np.min(a)

1

In [31]:
np.argmax(a)

3

In [33]:
np.argmin(a)

0

In [34]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [35]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [36]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [37]:
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128])

# Linspace() ==> This function returns value between a given range and with a same gap between consicutive elements .

In [41]:
a=np.linspace(1,3,10)
a

array([1.        , 1.22222222, 1.44444444, 1.66666667, 1.88888889,
       2.11111111, 2.33333333, 2.55555556, 2.77777778, 3.        ])

In [43]:
np.random.seed(122)
a=np.random.randint(1,21,9).reshape(3,3)
a

array([[16, 11, 13],
       [17, 13, 16],
       [ 3, 16, 11]])

In [44]:
np.sum(a)

116

In [45]:
np.sum(a,axis=1)

array([40, 46, 30])

In [46]:
np.min(a)

3

In [47]:
np.max(a)

17

In [48]:
np.cumsum(a)

array([ 16,  27,  40,  57,  70,  86,  89, 105, 116], dtype=int32)

# np.unique(arr , return_index = True , return_counts = True) 

returns 3 array:

1 . the array with unique values . 

2 . the array with respective index value . 

3 . the array with counting of frequencey .

In [49]:
a=np.array([10,20,30,40,50,10,60,20,30,40])
np.unique(a, return_index=True, return_counts=True)

(array([10, 20, 30, 40, 50, 60]),
 array([0, 1, 2, 3, 4, 6], dtype=int64),
 array([2, 2, 2, 2, 1, 1], dtype=int64))

# Horizontal And Vertical Stacking

In [50]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
a

array([1, 2, 3, 4])

In [51]:
b

array([5, 6, 7, 8])

In [52]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [53]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])