Q1. Write statement to import NumPy?

In [1]:
import numpy as np

Q2. Create an array using NumPy?

In [2]:
arr=np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

Q3. Create an array of 10 random integers?

In [3]:
random_integers=np.random.randint(2,30,10)
random_integers

array([19,  8, 24, 20, 25, 29, 13,  9, 20,  7])

Q4. Create an array of elements from 10-20?

In [4]:
arr=np.arange(10,21)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

Q5. Create an array which contains value 5,10 times?

In [6]:
arr=np.repeat(5,10)
arr

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

Q6. Create one dimensional array and convert that into 3*3 matrix?

In [7]:
arr=np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Q7 Create a 2D array of size 3*3 but all the elements should be between 0 to 1?

In [9]:
arr=np.random.rand(3,3)
arr

array([[0.07808262, 0.69509915, 0.49493589],
       [0.75974632, 0.70835104, 0.11735075],
       [0.96048942, 0.50450554, 0.01564352]])

Q8. Concatenate 2D array horizontally and vertically?

In [11]:
arr1=np.array([1,2,3,4]).reshape(2,2)
arr2=np.array([5,6,7,8]).reshape(2,2)
horizontal_concatenate=np.hstack((arr1,arr2))
vertical_concatenate=np.vstack((arr1,arr2))
print(f"Horizontally concatenated array =\n {horizontal_concatenate}")
print(f"Vertically concatenated array =\n {vertical_concatenate}")

Horizontally concatenated array =
 [[1 2 5 6]
 [3 4 7 8]]
Vertically concatenated array =
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
